const tg=window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand();tg.setHeaderColor?.('#080806');tg.setBackgroundColor?.('#080806');}

const titles=['Фундамент','Золотая жила','Сад изобилия','Полноводная река','Колодец предков','Хранитель порога','Скала','Солнце в зените','Плодородная земля','Открытая дверь','Рог изобилия','Мост','Крепость','Феникс','Источник','Якорь','Древо рода','Свеча в темноте','Жемчужина','Компас','Якорь на ноге','Золотая клетка','Тень великана','Пустой кошелёк','Песочные часы','Разбитая копилка','Лабиринт','Нищий с золотой чашей','Терновый куст','Слепой банкир','Дырявое ведро','Крыса в колесе','Спящий дракон','Зеркало кривое','Тонущий корабль','Оковы','Прокрустово ложе','Две маски','Лестница в небо','Засохший колодец','Сеятель','Мельница','Кузнец','Торговец','Строитель','Моряк','Алхимик','Пчела','Водопад','Воздушный змей','Весы','Змея, кусающая хвост','Ключ и замок','Птица в полёте','Радуга после грозы','Факел','Вулкан','Хамелеон','Уроборос разорванный','Золотой ребёнок'];
const cats=[...Array(20).fill('resource'),...Array(20).fill('shadow'),...Array(20).fill('action')];
const names={resource:'Ресурс и опора',shadow:'Тень и препятствия',action:'Действие и трансформация'};
const meanings=['Внутренняя опора','Скрытый ресурс','Изобилие и способность принимать','Движение и естественный поток','Память и наследие','Границы и переход','Устойчивость','Ясность и проявленность','Среда для роста','Возможность','Изобилие','Связь и переход','Защита','Обновление','Живой внутренний поток','Заземление','Корни и принадлежность','Надежда и ориентир','Ценность, рождённая опытом','Внутреннее направление','То, что удерживает','Комфорт, который ограничивает','Увеличенная страхом преграда','Ощущение нехватки','Время и нетерпение','Утрата старой опоры','Потеря направления','Неспособность увидеть имеющееся','Боль и сопротивление','Ошибочная оценка ценности','Утечка сил','Замкнутый цикл','Неиспользованная сила','Искажённое восприятие','Потеря курса','Зависимость','Чужие рамки','Расхождение внешнего и внутреннего','Погоня за недостижимым','Истощение','Начало действия','Ритм и переработка опыта','Создание через усилие','Обмен и взаимодействие','Последовательное создание','Движение в неизвестность','Превращение опыта','Труд и вклад','Освобождение энергии','Игра с ветром перемен','Баланс и выбор','Цикл и возвращение','Точное решение','Освобождение','Переход к новому этапу','Следующий шаг','Высвобождение накопленного','Гибкость','Разрыв старого цикла','Новое начало'];
const shadows=['Строить слишком быстро, не укрепив основание.','Искать ответ только снаружи и не замечать собственный запас сил.','Считать, что принимать легче, чем позволять себе получать.','Пытаться удержать поток вместо того, чтобы войти в его движение.','Жить чужими денежными сценариями, не замечая их происхождения.','Стоять перед новой дверью дольше, чем нужно.','Сомневаться в себе именно тогда, когда нужна выдержка.','Прятать талант там, где пришло время его проявить.','Ожидать урожай раньше, чем корни успели укрепиться.','Ждать разрешения войти в возможность, которая уже открыта.','Бояться принимать то, что приходит легко.','Оставаться на прежнем берегу из-за страха перемен.','Защищать накопленное так сильно, что оно перестаёт жить.','Считать прошлую потерю окончательной.','Искать разовый источник вместо создания устойчивого потока.','Путать стабильность с неподвижностью.','Нести семейную историю как обязанность вместо опоры.','Гасить внутренний голос внешним шумом.','Недооценивать то, что было создано через опыт.','Идти по чужому маршруту, хотя внутренний уже известен.','Сохранять цепь даже тогда, когда корабль уже ушёл.','Менять свободу на привычную безопасность.','Позволять страху увеличивать реальный масштаб проблемы.','Воспринимать временную пустоту как окончательную нехватку.','Требовать результата раньше времени.','Держаться за разрушенную форму только из привычки.','Усложнять путь, когда решение находится рядом.','Не замечать ценность того, что уже есть.','Отказываться от движения из-за боли на пути.','Принимать цену за ценность и наоборот.','Не замечать маленькие утечки, которые становятся большими.','Повторять один сценарий, ожидая другого результата.','Хранить силу, которой давно пора пользоваться.','Верить искажённому отражению больше, чем фактам.','Продолжать курс после первого сигнала тревоги.','Считать обязательство вечным, даже когда ключ рядом.','Пытаться соответствовать чужому размеру.','Прятать настоящие чувства за удобной ролью.','Выбирать короткий путь с высокой ценой.','Пытаться оживить источник, который уже исчерпан.','Откладывать посев до идеальных условий.','Делать много, но без ритма и системы.','Ждать результата без готовности вложить усилие.','Обмениваться ценностью, забывая о собственной цене.','Строить без плана и последовательности.','Бояться движения, потому что берег привычнее.','Не превращать опыт в новый ресурс.','Недооценивать силу регулярной маленькой работы.','Бояться масштаба собственных возможностей.','Отпускать контроль слишком сильно или держать его слишком крепко.','Возвращаться к старому циклу автоматически.','Искать универсальный ключ вместо точного решения.','Думать, что свобода требует постоянного напряжения.','Не замечать, что трудный этап уже заканчивается.','Долго готовиться к шагу, который уже виден.','Держать накопленное напряжение внутри.','Менять форму, забывая о сути.','Разрушать старое, не оставляя места новому.','Считать лёгкость несерьёзностью.'];
const directions=['Укрепи основание и только потом добавляй следующий этаж.','Посмотри, какой ресурс уже находится в твоих руках.','Разреши себе принять результат без чувства вины.','Иди туда, где энергия движется естественно.','Отдели свой сценарий от унаследованного.','Сделай шаг через порог, не требуя полной гарантии.','Останься устойчивым, даже если вокруг меняется погода.','Покажи миру то, что умеешь.','Дай времени сделать свою работу.','Войди в открытую возможность одним конкретным действием.','Не отталкивай то, что приходит с пользой.','Перейди от намерения к движению.','Защищай важное, но оставляй ему пространство расти.','Используй прошлое как материал для нового этапа.','Создавай источник, который можно поддерживать.','Закрепи то, что уже работает.','Возьми из корней поддержку, а не ограничения.','Прислушайся к тихому внутреннему знанию.','Признай ценность своей работы и опыта.','Проверь направление перед следующим шагом.','Назови то, что удерживает тебя, и начни ослаблять цепь.','Проверь, не стала ли безопасность слишком дорогой.','Раздели реальную преграду и страх перед ней.','Оставь место для нового, не называя его нехваткой.','Уважай время процесса.','Позволь старой форме закончиться.','Упрости путь до одного следующего действия.','Посмотри на то, чем уже владеешь, новым взглядом.','Не требуй от себя проходить через боль вслепую.','Пересмотри, чему ты отдаёшь настоящую ценность.','Закрой одну маленькую утечку сегодня.','Измени повторяющееся действие, а не только намерение.','Разбуди ресурс, который давно лежит без движения.','Проверь, соответствует ли твой внутренний образ реальности.','Реагируй на первый сигнал, а не на последний.','Посмотри, где обязательство можно пересобрать.','Не измеряй себя чужой меркой.','Сними роль, которая больше не нужна.','Не путай скорость с дорогой.','Ищи новый источник энергии и дохода.','Посей то, что хочешь увидеть через время.','Создай рабочий ритм.','Преврати усилие в конкретный результат.','Обменивайся ценностью честно и ясно.','Построй систему, которая работает без постоянного хаоса.','Двигайся, даже если берег ещё виден.','Преврати обычное действие в ценность.','Делай небольшое, но регулярно.','Разреши себе увеличить масштаб.','Удерживай баланс между свободой и управлением.','Заметь повтор и измени его точку входа.','Назови точную задачу, вместо общей тревоги.','Позволь движению стать легче.','Признай завершение трудного этапа.','Сделай следующий шаг, не весь путь.','Дай накопленной энергии выйти в действие.','Оставь себе возможность менять форму.','Закрой старый цикл осознанно.','Начни с лёгкости, а не с борьбы.'];
const cards=titles.map((title,i)=>({id:i+1,title,category:cats[i],meaning:meanings[i],shadow:shadows[i],direction:directions[i]}));

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let history=JSON.parse(localStorage.getItem('oracleHistory')||'[]');
let currentQuestion='', spreadSize=3, spreadCards=[];

function haptic(type='light'){try{tg?.HapticFeedback?.impactOccurred?.(type)}catch(e){}}
function screen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='history')renderHistory();haptic('light')}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function random(pool=cards){return pool[Math.floor(Math.random()*pool.length)]}
function save(entry){history.unshift({...entry,at:new Date().toISOString()});history=history.slice(0,30);localStorage.setItem('oracleHistory',JSON.stringify(history))}
function cardMini(c,face=false){return `<button class="mini-card ${face?'mini-face':''}" data-id="${c.id}"><span>${String(c.id).padStart(2,'0')}</span><i>✦</i><b>${c.title}</b></button>`}

function beginQuestion(){const q=$('#homeQuestion').value.trim();currentQuestion=q;if(!q){$('#homeQuestion').focus();toast('Сначала расскажи картам, о чём ты пришёл спросить.');return}screen('ritual');$('#ritualQuestion').textContent='«'+q+'»';$('#ritualStep').textContent='КАРТЫ СЛУШАЮТ';$('#ritualText').textContent='Не ищи ответ. Просто побудь со своим вопросом.';$('#ritualAction').textContent='Я готов';haptic('medium')}
function startDraw(){screen('draw');resetDraw()}
function startFromHome(){beginQuestion()}
function ritualReady(){const q=$('#ritualQuestion').textContent.replace(/^«|»$/g,'');currentQuestion=q;screen('draw');resetDraw();$('#drawStep').textContent='ПЕРЕД ТЕБЯ — КОЛОДА';$('#drawHint').textContent='Сосредоточься на своём вопросе. Когда почувствуешь готовность — прикоснись к колоде.';haptic('medium')}
function resetDraw(){const big=$('#big');big.className='oracle-card face-down';big.innerHTML='<div class="card-back-inner"><span>К</span><i>✦</i><small>КАРТЫ ЗНАЮТ</small></div>';$('#drawStep').textContent='ОДНА КАРТА';$('#drawHint').textContent='Сформулируй вопрос внутри себя и открой карту.';$('#reveal').textContent='Открыть карту';$('#reveal').disabled=false}
function reveal(){const c=random();$('#reveal').disabled=true;haptic('heavy');const big=$('#big');big.classList.add('turning');setTimeout(()=>{big.classList.remove('face-down','turning');big.innerHTML=`<div class="card-face"><span class="card-no">${String(c.id).padStart(2,'0')}</span><div class="card-symbol">✦</div><strong>${c.title}</strong><small>${names[c.category]}</small></div>`;$('#drawStep').textContent='КАРТА ОТКРЫТА';$('#drawHint').textContent='«'+c.meaning+'»';showReading(c,currentQuestion);save({type:'card',question:currentQuestion,cards:[c.id]});haptic('success')},650)}
function showReading(c,q){$('#reading').classList.add('visible');$('#readingQuestion').textContent=q?'Ты спросил: «'+q+'»':'Твой вопрос был услышан картами.';$('#readingLead').textContent=leadFor(c,q);$('#readingShadow').textContent=c.shadow;$('#readingDirection').textContent=c.direction;$('#readingNext').textContent=questionFor(c);$('#another').textContent='Продолжить диалог';setTimeout(()=>$('#reading').scrollIntoView({behavior:'smooth',block:'start'}),180)}
function leadFor(c,q){const starts={resource:'Эта карта пришла из пространства опоры. ',shadow:'Эта карта пришла из пространства тени. ',action:'Эта карта пришла из пространства действия. '};return starts[c.category]+(q?`На твой вопрос она отвечает через образ «${c.title}»: сейчас важно увидеть не только то, что происходит снаружи, но и то, какую роль ты сам играешь в этой ситуации.`:`Образ «${c.title}» предлагает посмотреть на то, что происходит внутри и вокруг тебя прямо сейчас.`)+` Здесь есть тема: ${c.meaning.toLowerCase()}.`}
function questionFor(c){return `Что изменится, если я перестану ${c.shadow.toLowerCase().replace(/[.]$/,'')}?`}
function another(){currentQuestion='';$('#homeQuestion').value='';$('#reading').classList.remove('visible');screen('home');setTimeout(()=>$('#homeQuestion').focus(),300)}

function openSpread(){const q=$('#homeQuestion').value.trim();currentQuestion=q;$('#spreadQuestion').value=q;screen('spread');$('#spreadResult').innerHTML='';$('#spreadIntro').textContent=q?'Вопрос принят. Теперь карты покажут его с трёх сторон.':'Сформулируй вопрос — так расклад станет личным.'}
function doSpread(){const q=$('#spreadQuestion').value.trim();if(!q){$('#spreadQuestion').focus();toast('Напиши вопрос, прежде чем раскладывать карты.');return}currentQuestion=q;let pool=[...cards];spreadCards=[];for(let i=0;i<spreadSize;i++){const c=random(pool);spreadCards.push(c);pool=pool.filter(x=>x.id!==c.id)}$('#spreadResult').innerHTML=spreadCards.map((c,i)=>`<div class="spread-card-wrap"><small>${['ЧТО ПРОИСХОДИТ','ЧТО СКРЫТО','КУДА ДВИГАТЬСЯ','ЧТО МЕШАЕТ','ЧТО ОТКРОЕТСЯ'][i]}</small>${cardMini(c)}</div>`).join('')+`<button id="interpretSpread" class="gold wide">Открыть историю расклада</button>`;$$('.mini-card').forEach(x=>x.onclick=()=>detail(+x.dataset.id));$('#interpretSpread').onclick=()=>interpretSpread();save({type:'spread',question:q,cards:spreadCards.map(c=>c.id),size:spreadSize});haptic('medium')}
function interpretSpread(){const result=$('#spreadReading');result.innerHTML=`<div class="reading-block"><small>ТВОЙ ВОПРОС</small><p>«${esc(currentQuestion)}»</p></div>`+spreadCards.map((c,i)=>`<article><small>${['01 · ЧТО ПРОИСХОДИТ','02 · ЧТО СКРЫТО','03 · КУДА ДВИГАТЬСЯ','04 · ЧТО МЕШАЕТ','05 · ЧТО ОТКРОЕТСЯ'][i]}</small><h3>${c.title}</h3><p>${leadFor(c,currentQuestion)}</p><div class="reading-sub"><b>Тень</b><span>${c.shadow}</span></div><div class="reading-sub"><b>Направление</b><span>${c.direction}</span></div></article>`).join('')+`<button class="gold wide" onclick="screen('home')">Задать новый вопрос</button>`;result.classList.add('visible');result.scrollIntoView({behavior:'smooth',block:'start'})}
function detail(id){const c=cards.find(x=>x.id===id);if(!c)return;$('#detailBox').innerHTML=`<div class="detail-card"><div class="detail-symbol">✦</div><small>${String(c.id).padStart(2,'0')} · ${names[c.category].toUpperCase()}</small><h2>${c.title}</h2><em>${c.meaning}</em><section><b>ОБРАЗ</b><p>${leadFor(c,'')}</p></section><section><b>ТЕНЬ</b><p>${c.shadow}</p></section><section><b>ВОПРОС К СЕБЕ</b><p>${questionFor(c)}</p></section><section><b>НАПРАВЛЕНИЕ</b><p>${c.direction}</p></section></div>`;screen('detail')}
function renderDeck(){const filter=$('#deckFilter').value;const list=filter==='all'?cards:cards.filter(c=>c.category===filter);$('#grid').innerHTML=list.map(cardMini).join('');$$('#grid .mini-card').forEach(x=>x.onclick=()=>detail(+x.dataset.id));$('#deckCount').textContent=`${list.length} карт`}
function renderHistory(){const box=$('#historyList');if(!history.length){box.innerHTML='<div class="empty"><span>✦</span><p>Здесь будут храниться ваши встречи с колодой.</p><small>Первый вопрос можно задать на главной.</small></div>';return}box.innerHTML=history.map(h=>{const d=new Date(h.at).toLocaleString('ru-RU',{day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'});return `<article class="history-item"><small>${h.type==='card'?'ОДНА КАРТА':`РАСКЛАД · ${h.size} КАРТ`}</small><time>${d}</time>${h.question?`<p>«${esc(h.question)}»</p>`:''}<div>${h.cards.map(id=>{const c=cards.find(x=>x.id===id);return c?`<button data-id="${id}">${String(id).padStart(2,'0')} · ${c.title}</button>`:''}).join('')}</div></article>`}).join('');$$('.history-item button').forEach(x=>x.onclick=()=>detail(+x.dataset.id))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}

$('#askBtn').onclick=startFromHome;$('#ritualAction').onclick=ritualReady;$('#big').onclick=()=>{if($('#big').classList.contains('face-down'))reveal()};$('#reveal').onclick=reveal;$('#another').onclick=another;$('#spreadStart').onclick=doSpread;$('#spread1').onclick=()=>{spreadSize=1;$$('.spread-choice').forEach(x=>x.classList.remove('active'));$('#spread1').classList.add('active')};$('#spread3').onclick=()=>{spreadSize=3;$$('.spread-choice').forEach(x=>x.classList.remove('active'));$('#spread3').classList.add('active')};$('#spread5').onclick=()=>{spreadSize=5;$$('.spread-choice').forEach(x=>x.classList.remove('active'));$('#spread5').classList.add('active')};$('#newQuestion').onclick=another;$('#deckFilter').onchange=renderDeck;$('#clearHistory').onclick=()=>{history=[];localStorage.removeItem('oracleHistory');renderHistory();toast('История очищена')};
$$('[data-screen]').forEach(x=>x.onclick=()=>screen(x.dataset.screen));
$('#openSpread').onclick=openSpread;
renderDeck();
